version: '3.8'

services:
  api:
    build:
      context: ../
      dockerfile: infrastructure/Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      - API_SECRET=your_api_secret_here
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      - ../models:/app/models
    depends_on:
      - mlflow
      - prometheus

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.8.0
    ports:
      - "5000:5000"
    volumes:
      - mlflow-data:/mlflow
    command: mlflow server --host 0.0.0.0

  prometheus:
    image: prom/prometheus:v2.45.0
    ports:
      - "9090:9090"
    volumes:
      - ../monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus

  grafana:
    image: grafana/grafana:10.2.0
    ports:
      - "3000:3000"
    volumes:
      - ../monitoring/grafana_dashboards:/etc/grafana/provisioning/dashboards
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus

  frontend:
    build:
      context: ../frontend
      dockerfile: ../infrastructure/Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - api

volumes:
  mlflow-data:
  prometheus-data:
  grafana-data:
